# Generated by Django 4.2.25 on 2025-11-04 04:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssociacaoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Sistema do Pescador de Ipixuna', max_length=200)),
                ('cnpj', models.CharField(blank=True, max_length=18)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('cep', models.CharField(blank=True, max_length=9)),
                ('valor_mensalidade_padrao', models.DecimalField(decimal_places=2, default=25.0, max_digits=8)),
            ],
            options={
                'verbose_name': 'Configuração da Associação',
                'verbose_name_plural': 'Configurações da Associação',
            },
        ),
        migrations.CreateModel(
            name='Pescador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(help_text='Formato: 000.000.000-00', max_length=14, unique=True)),
                ('data_nascimento', models.DateField()),
                ('rgp', models.CharField(max_length=30, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('data_associacao', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(help_text='Formato: 00000-000', max_length=9)),
                ('pescador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='associados.pescador')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RG', 'RG'), ('CPF', 'CPF'), ('RGP', 'RGP'), ('COMPROVANTE_ENDERECO', 'Comprovante de Endereço'), ('FOTO', 'Foto 3x4'), ('OUTRO', 'Outro')], max_length=30)),
                ('arquivo', models.FileField(upload_to='documentos/')),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('pescador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='associados.pescador')),
            ],
            options={
                'ordering': ['-data_upload'],
            },
        ),
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(help_text='Use o primeiro dia do mês (AAAA-MM-01)')),
                ('valor', models.DecimalField(decimal_places=2, default=25.0, max_digits=8)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('isento', 'Isento')], default='pendente', max_length=10)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('forma_pagamento', models.CharField(blank=True, max_length=50)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('pescador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensalidades', to='associados.pescador')),
            ],
            options={
                'ordering': ['-competencia'],
                'unique_together': {('pescador', 'competencia')},
            },
        ),
    ]
