# Generated by Django 4.2.25 on 2025-11-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='associacaoconfig',
            name='presidente',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='pescador',
            name='seguro_defeso_pedido',
            field=models.BooleanField(default=False),
        ),
    ]
