# Generated by Django 4.2.25 on 2025-11-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0002_associacaoconfig_presidente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='associacaoconfig',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
