# Generated by Django 4.2.25 on 2025-11-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0003_associacaoconfig_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='associacaoconfig',
            name='assinatura_presidente',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/'),
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='recibo_numero',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='recibo_token',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='pescador',
            name='rg',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pescador',
            name='rg_orgao_emissor',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
