# Generated by Django 4.2.25 on 2025-11-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0004_associacaoconfig_assinatura_presidente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaixaLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10)),
                ('categoria', models.CharField(help_text='Ex.: Mensalidade, Salário, Aluguel, Material', max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data', '-criado_em'],
            },
        ),
    ]
